# Predicción lineal

 En la figura se observa un filtro forward predictor con una estructura FIR

<img src="predictor.png" alt="Predictor lineal"/>

Las entradas a los taps son $u(i-1), u(i-2), ..., u(i-M)$. La idea de este filtro es predecir el valor siguiente de la señal $u(i)$, denotado $\hat{u}(i)$.

El objetivo es encontrar el vector de taps *${\hat{w}}$* que minimice la suma cuadrática de los errores de predicción, $e_f$

$$e_f = \sum_{i=M+1}^{N} \left|f_M(i)\right|^2$$

#### Encontrar:

1. La matriz de $M$ por $M$ de correlación los taps de entrada 

2. El vector de correlación cruzada $M$ por $1$ entre los taps de entrada del predictor y la respuesta deseada $u(i)$ 

3. El valor mínimo de $e_f$

4. El vector de taps *${\hat{w}}$*

5. Una vez obtenida la ecuación del filtro predictor, calcular el filtro para $N$ valores de una realización de la siguiente señal:

$$u(i) = sen(2\pi\omega_0i + \phi_0) + 0.02n(i)$$

siendo $\omega_0 = 3, \phi_0 = \pi / 4$ y $n(i)$ un ruido gaussiano de varianza unitaria. Tomar N = 100 y M = 4

6. Ver cómo se comporta el filtro (es decir, su capacidad de predicción) para otras realizaciones del mismo proceso.

#### Consejos orientativos:
* Pensar a $N$ como un valor mayor a $M$. Es decir, $N$ representa la cantidad TOTAL de puntos de $u(i)$ y $M$ es la cantidad de taps del filtro. En un momento dado, hay $M$ puntos de $u(i)$ dentro del filtro.
* Podemos pensar que el primer valor válido de $u$ es $u(1)$, es decir la secuencia empieza $u(1), u(2), \dots ,u(N)$
* El filtro produce resultados desde $i = M+1$ hasta $i = N$, es decir, $N-M$ predicciones.
* Al ser las señales reales, los valores hermíticos de los vectores o matrices son los traspuestos.
* Para multiplicación de matrices, utilizar @. Por ejemplo:

In [29]:
import numpy as np
a = np.array([[1,2,3],[2,3,1]])
b = np.array([-1,4,3])
c = a @ b
c

array([16, 13])

# Resolución

Nota: En Filtrado.pdf (pag. 27) se expresa la forma de la matriz que se debe generar de acuerdo a un vector dado con las señales de entrada.
La señal de entrada se denomina ‘u’ y tiene ‘n’ coeficientes.
El objetivo es estimar cuál es el filtro que hace que los ‘n’ coeficientes de ‘u’ entreguen la mejor aproximación por un filtro lineal de nuestra señal deseada ‘d’ (que debemos conocer). Este filtro representa el caso general, filtro adaptativo, y en el TP1 vimos el filtro adaptado determinista que es un caso especial a partir de este. Cabe aclarar que este no es el filtro de winner porque para calcularlo necesito conocer la estadistica de la señal de entrada y la correlación cruzada con la señal deseada.

Por convenencia se define una matriz A hermitica (transpuesta y conjugada) que se arma con los N vectores de entrada que vamos teniendo en el primer vector que ya esta cargado en el filtro, que va desde el u(M) hasta el u(1).
Cuando pasa un tiempo tenemos el segundo vector columna con u(M+1) hasta u(2).. el último va desde u(N) hasta (N-M+1)

Ejemplo:
Para el vector u = [3, 2, 1, -1]
Definiendo M = 2 (cantidad de taps del filtro)

La matriz correspondiente es la siguiente:

instante 1	instante 2	instante 3<br/>
u2=2		u3=1		u4=-1<br/>
u1=3		u2=2		u3=1<br/>

M establece la cantidad de filas de la matriz y la cantidad de columnas esta dada por: (Cantidad de muestras) - (cantidad de taps del filtro) + 1

### 1) Encontrar la matriz de M por N de correlación los taps de entrada

In [30]:
u = [3, 2, 1, -1] # vector de ejemplo 
N = 4 # elementos del vector
M = 2 # cantidad de taps del filtro

matriz = np.zeros((M, N-M+1))
for i in range(N-M+1):
    instante = u[i:M+i]
    matriz[:,i] = instante[::-1]

matriz

array([[ 2.,  1., -1.],
       [ 3.,  2.,  1.]])

In [31]:
#Al ser valores reales, la hermítica es directamente la traspuesta (no hace falta conjugar los valores).
hermitica = matriz.transpose()  

hermitica


array([[ 2.,  3.],
       [ 1.,  2.],
       [-1.,  1.]])

### 2) El vector de correlación cruzada  𝑀  por  1  entre los taps de entrada del predictor y la respuesta deseada  𝑢(𝑖)

In [32]:
d = np.array([ 2, 1, 1/34  ]) # vector deseado de ejemplo
dh = d.transpose() # no funciona...

#El vector z es la matriz hermítica por el vector de la respuesta deseada
#z = hermitica @ dh
#z

### 3) El valor mínimo de  𝑒𝑓

In [33]:
#Existe un error de aproximación generado en la señal al analizarla y es blanco, afecta por igual, y es aditivo.

#El minimo error cuadratico medio entre la senial obtenida y la deseada esta determinado por la sig formula:
Emin = dh @ d  -  dh @ matriz @ np.linalg.inv(hermitica @ matriz) @ hermitica @ d


ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)

### 4) El vector de taps  𝑤̂ 

In [ ]:
# El vector de taps esta determinado por la sig formula:
w = np.linalg.inv(hermitica @ matriz) @ hermitica @ d

### 5) Calcular el filtro para  𝑁  valores de una realización de la señal 𝑢(𝑖)=𝑠𝑒𝑛(2𝜋𝜔0𝑖+𝜙0)+0.02𝑛(𝑖) siendo  𝜔0=3,𝜙0=𝜋/4  y  𝑛(𝑖)  un ruido gaussiano de varianza unitaria. Tomar N = 100 y M = 4.

### 6) Ver cómo se comporta el filtro (es decir, su capacidad de predicción) para otras realizaciones del mismo proceso.